In [0]:
import numpy as np
c=np.array([[0,1,2],[3,4,5]])
c,len(c),len(c[0]),c.shape,type(c)

(array([[0, 1, 2],
        [3, 4, 5]]), 2, 3, (2, 3), numpy.ndarray)

In [0]:
import numpy as np
d=np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22]]])
d,d.shape,len(d),len(d[0]),len(d[0][0])

(array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[11, 12, 13, 14],
         [15, 16, 17, 18],
         [19, 20, 21, 22]]]), (2, 3, 4), 2, 3, 4)

In [0]:
import numpy as np
a = np.arange(12)
a,a.shape,type(a)

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,), numpy.ndarray)

In [0]:
b=a.reshape(3,4)
b,b.shape,type(b)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]), (3, 4), numpy.ndarray)

In [0]:
a=np.array([[1,2,3],[4,5,6]])

In [0]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
a,a.T

(array([[1, 2, 3],
        [4, 5, 6]]), array([[1, 4],
        [2, 5],
        [3, 6]]))

In [0]:
import numpy as np
x=np.array([[1,2],[3,4],[5,6]])
y=x[[0,1],[1,1]]
x,x.shape,y,y.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]), (3, 2), array([2, 4]), (2,))

In [0]:
x=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])
y = x[1:4,[1,2]] 
x, x.shape, y, y.shape 

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]), (4, 3), array([[ 4,  5],
        [ 7,  8],
        [10, 11]]), (3, 2))

In [0]:
 a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 idx = np.array([True, False, True, False, True, False, True, False, True, False])
 a[idx],a[a%2==0]

(array([0, 2, 4, 6, 8]), array([0, 2, 4, 6, 8]))

In [0]:
x=np.array([[0,1,2],[np.nan,4,5],[6,7,8],[9,10,11]])
x,x[x>5],x[np.isnan(x)]

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in greater
  


(array([[ 0.,  1.,  2.],
        [nan,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]]), array([ 6.,  7.,  8.,  9., 10., 11.]), array([nan]))

In [0]:
c=np.array([[0,1,2],[3,4,5]])
c,len(c),len(c[0]),c.shape,type(c),c.itemsize

(array([[0, 1, 2],
        [3, 4, 5]]), 2, 3, (2, 3), numpy.ndarray, 8)

In [0]:
d=np.array([2,3,4])
d,len(d),d.shape,type(d)

(array([2, 3, 4]), 3, (3,), numpy.ndarray)

In [0]:
c*d

array([[ 0,  3,  8],
       [ 6, 12, 20]])

In [0]:
x = np.array([1, 2, 3, 1])
x.sum(), x.max(), x.argmin(), x.argmax(), x.mean(), np.median(x), x.std()

(7, 3, 0, 2, 1.75, 1.5, 0.82915619758885)

In [0]:
np.sum(x),np.min(x)


(7, 1)

In [0]:
x = np.array([[0, 1, 2], [7,8,9], [2, 3, 4], [4, 5, 6]])
x.sum(), x.max(),x.std()

(51, 9, 2.7118566825454966)

In [0]:
x=np.array([[1,3,5,7],[2,4,6,8]])
x,type(x),x.ndim,x.shape,len(x),x[0],x[:,3]

(array([[1, 3, 5, 7],
        [2, 4, 6, 8]]),
 numpy.ndarray,
 2,
 (2, 4),
 2,
 array([1, 3, 5, 7]),
 array([7, 8]))

In [0]:
x.sum(axis=0),x.sum(axis=1),np.sum(x[0]),np.sum(x[:,3])

(array([ 3,  7, 11, 15]), array([16, 20]), 16, 15)

In [0]:
d=np.array([[[1,3,5],[5,6,7]],[[5,6,7],[5,6,7]]])
d,d.dtype,type(d),d.ndim,d.shape,len(d),d.sum(axis=2)

(array([[[1, 3, 5],
         [5, 6, 7]],
 
        [[5, 6, 7],
         [5, 6, 7]]]),
 dtype('int64'),
 numpy.ndarray,
 3,
 (2, 2, 3),
 2,
 array([[ 9, 18],
        [18, 18]]))

In [0]:
#{'num':'1', 'name':'김철수','kor':90, 'eng':80, 'math':85, 'total':0, 'avg':0.0}
a= np.array([[1, 90, 80, 85, 0, 0.0, 0],[2, 90, 85, 90, 0, 0.0, 0],[3, 80, 80, 80, 0, 0.0, 0]],dtype=np.int64)

In [0]:
a,type(a)

(array([[ 1, 90, 80, 85,  0,  0,  0],
        [ 2, 90, 85, 90,  0,  0,  0],
        [ 3, 80, 80, 80,  0,  0,  0]]), numpy.ndarray)

In [0]:
a[:,4]=np.sum(a[:,1:4],axis=0)     #total값 생성

In [0]:
a

array([[  1,  90,  80,  85, 260,   0,   0],
       [  2,  90,  85,  90, 245,   0,   0],
       [  3,  80,  80,  80, 255,   0,   0]])

In [0]:
a[:,5]=np.array(a[:,4]/3)            #평균값 생성
a

array([[  1,  90,  80,  85, 260,  86,   0],
       [  2,  90,  85,  90, 245,  81,   0],
       [  3,  80,  80,  80, 255,  85,   0]])

In [0]:
b=np.sum(a[:,1]/3,dtype=np.int64)
print("국어점수의 평균은",b,"점입니다.")
c=np.sum(a[:,2]/3,dtype=np.int64)
print("영어점수의 평균은",c,"점입니다.")
d=np.sum(a[:,3]/3,dtype=np.int64)
print("수학점수의 평균은",d,"점입니다.")

국어점수의 평균은 86 점입니다.
영어점수의 평균은 80 점입니다.
수학점수의 평균은 84 점입니다.
