In [0]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]))

In [0]:
np.concatenate((a,b)),np.concatenate((a,b),axis=0),np.concatenate((a,b),axis=1)

(array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]), array([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]]), array([[1, 2, 5, 6],
        [3, 4, 7, 8]]))

In [0]:
a=np.arange(9)
b=np.split(a,3)
a,type(a),b,type(b)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 numpy.ndarray,
 [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])],
 list)

In [0]:
a=np.array([[1,2,3],[4,5,6]])

In [0]:
b=np.resize(a,(3,2))
b,b.shape

(array([[1, 2],
        [3, 4],
        [5, 6]]), (3, 2))

In [0]:
c=a.reshape(3,2)

In [0]:
c

array([[1, 2],
       [3, 4],
       [5, 6]])

In [0]:
a = np.array([[1,2],[3,4],[5,6]])

In [0]:
np.insert(a,1,[11,12],axis=0)

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [0]:
np.insert(a,2,11,axis=1)

array([[ 1,  2, 11],
       [ 3,  4, 11],
       [ 5,  6, 11]])

In [0]:
b=[[11,12],[13,14]]

In [0]:
np.insert(a,1,b,axis=0)

array([[ 1,  2],
       [11, 12],
       [13, 14],
       [ 3,  4],
       [ 5,  6]])

In [0]:
a=np.arange(12).reshape(3,4)

In [0]:
a,np.delete(a,5),np.delete(a,1,axis=1),np.delete(a,[0,2],axis=1)

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([ 0,  1,  2,  3,  4,  6,  7,  8,  9, 10, 11]),
 array([[ 0,  2,  3],
        [ 4,  6,  7],
        [ 8, 10, 11]]),
 array([[ 1,  3],
        [ 5,  7],
        [ 9, 11]]))

In [48]:
a=np.array([1,2,3],[1,0,-1],[4,5,6])
b=np.array([-1,1],[3,2],[-2,5])

ValueError: ignored