In [0]:
import numpy as np

In [0]:
student_score = [
 [1, 90, 80, 85, 0, 0.0, 0, 0],
 [2, 88, 85, 90, 0, 0.0, 0, 0],
 [3, 32, 85, 90, 0, 0.0, 0, 0],
 [4, 42, 75, 93, 0, 0.0, 0, 0],
 [5, 82, 86, 88, 0, 0.0, 0, 0]
]
ndarray = np.array(student_score)
ndarray, type(ndarray), type(ndarray[0])

(array([[ 1., 90., 80., 85.,  0.,  0.,  0.,  0.],
        [ 2., 88., 85., 90.,  0.,  0.,  0.,  0.],
        [ 3., 32., 85., 90.,  0.,  0.,  0.,  0.],
        [ 4., 42., 75., 93.,  0.,  0.,  0.,  0.],
        [ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]]),
 numpy.ndarray,
 numpy.ndarray)

In [0]:
ndarray[:,0], ndarray[4,:] , ndarray[2:5,1:5]

(array([1., 2., 3., 4., 5.]),
 array([ 5., 82., 86., 88.,  0.,  0.,  0.,  0.]),
 array([[32., 85., 90.,  0.],
        [42., 75., 93.,  0.],
        [82., 86., 88.,  0.]]))

In [0]:
np.max(ndarray)

93.0

In [0]:
x=np.array([[0,1,2],[1,2,3],[2,3,4],[4,5,6]])
x

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [0]:
x*[0,1,0.1]

array([[0. , 1. , 0.2],
       [0. , 2. , 0.3],
       [0. , 3. , 0.4],
       [0. , 5. , 0.6]])

In [0]:
(ndarray == 0), (ndarray[:,1:5] > 20), (ndarray[:,1:5] > 20) & (ndarray[:,1:5] > 80)

(array([[False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True],
        [False, False, False, False,  True,  True,  True,  True]]),
 array([[ True,  True,  True, False],
        [ True,  True,  True, False],
        [ True,  True,  True, False],
        [ True,  True,  True, False],
        [ True,  True,  True, False]]),
 array([[ True, False,  True, False],
        [ True,  True,  True, False],
        [False,  True,  True, False],
        [False, False,  True, False],
        [ True,  True,  True, False]]))

In [0]:
ndarray[(ndarray==0)]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [0]:
ndarr = ndarray[:,1:5]
ndarr

array([[90., 80., 85.,  0.],
       [88., 85., 90.,  0.],
       [32., 85., 90.,  0.],
       [42., 75., 93.,  0.],
       [82., 86., 88.,  0.]])

In [0]:
ndarr[(ndarr>20)]

array([90., 80., 85., 88., 85., 90., 32., 85., 90., 42., 75., 93., 82.,
       86., 88.])

In [0]:
a = np.array([[1,2,3],[3,4,5],[5,6,7]])

In [0]:
a

array([[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]])

In [0]:
np.insert(a,1,[11,12,13],axis = 0), np.insert(a,2,11,axis = 1)

(array([[ 1,  2,  3],
        [11, 12, 13],
        [ 3,  4,  5],
        [ 5,  6,  7]]), array([[ 1,  2, 11,  3],
        [ 3,  4, 11,  5],
        [ 5,  6, 11,  7]]))