In [0]:
import numpy as np

#{'num':'1', 'name':'김철수','kor':90, 'eng':80, 'math':85, 'total':0, 'avg':0.0}
a= np.array([[1, 90, 80, 85, 0, 0.0, 0],
             [2, 90, 85, 90, 0, 0.0, 0],
             [3, 80, 80, 80, 0, 0.0, 0]],dtype=np.int64)

In [5]:
a,type(a)

(array([[ 1, 90, 80, 85,  0,  0,  0],
        [ 2, 90, 85, 90,  0,  0,  0],
        [ 3, 80, 80, 80,  0,  0,  0]]), numpy.ndarray)

In [6]:
a[:,4]=np.sum(a[:,1:4],axis=1)     #total값 생성
a

array([[  1,  90,  80,  85, 255,   0,   0],
       [  2,  90,  85,  90, 265,   0,   0],
       [  3,  80,  80,  80, 240,   0,   0]])

In [7]:
a[:,5]=np.array(a[:,4]/3)            #평균값 생성
a

array([[  1,  90,  80,  85, 255,  85,   0],
       [  2,  90,  85,  90, 265,  88,   0],
       [  3,  80,  80,  80, 240,  80,   0]])

In [8]:
b=np.sum(a[:,1]/3,dtype=np.int64)          #과목별 평균값
print("국어점수의 평균은",b,"점입니다.")
c=np.sum(a[:,2]/3,dtype=np.int64)
print("영어점수의 평균은",c,"점입니다.")
d=np.sum(a[:,3]/3,dtype=np.int64)
print("수학점수의 평균은",d,"점입니다.")

국어점수의 평균은 86 점입니다.
영어점수의 평균은 80 점입니다.
수학점수의 평균은 84 점입니다.


In [9]:
e=np.sum(a[:,1:4]/9,dtype=np.float64)       #학급 평균값
print("학급 평균점수는",e,"점입니다.")

학급 평균점수는 84.44444444444443 점입니다.
