In [0]:
import numpy as np
from sklearn import datasets
wine= datasets.load_wine()
from sklearn import metrics

In [2]:
wine.keys()

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])

In [3]:
wine['data'],len(wine),type(wine)

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]), 5, sklearn.utils.Bunch)

In [4]:
x=np.array(wine['data'])
x,type(x),x.shape

(array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]]), numpy.ndarray, (178, 13))

In [0]:
wine['target']    #0=class_0 ,1=class_1,2=class_2

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [0]:
wine['target_names']    #종속 변수 이름리스트

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [0]:
wine['feature_names']   # data의 column명

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

In [0]:
print(wine.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [12]:
for i in range(len(wine.feature_names)):
  print(wine.feature_names[i])
  print("평균:",round(np.mean(wine.data[:,i]),1))
  print("중간값:",round(np.median(wine.data[:,i]),1))
  print("표준편차:",round(np.std(wine.data[:,i]),1))
  print("최대값:",np.max(wine.data[:,i]))
  print("최소값:",np.min(wine.data[:,i]))
  print("\n")


alcohol
평균: 13.0
중간값: 13.0
표준편차: 0.8
최대값: 14.83
최소값: 11.03


malic_acid
평균: 2.3
중간값: 1.9
표준편차: 1.1
최대값: 5.8
최소값: 0.74


ash
평균: 2.4
중간값: 2.4
표준편차: 0.3
최대값: 3.23
최소값: 1.36


alcalinity_of_ash
평균: 19.5
중간값: 19.5
표준편차: 3.3
최대값: 30.0
최소값: 10.6


magnesium
평균: 99.7
중간값: 98.0
표준편차: 14.2
최대값: 162.0
최소값: 70.0


total_phenols
평균: 2.3
중간값: 2.4
표준편차: 0.6
최대값: 3.88
최소값: 0.98


flavanoids
평균: 2.0
중간값: 2.1
표준편차: 1.0
최대값: 5.08
최소값: 0.34


nonflavanoid_phenols
평균: 0.4
중간값: 0.3
표준편차: 0.1
최대값: 0.66
최소값: 0.13


proanthocyanins
평균: 1.6
중간값: 1.6
표준편차: 0.6
최대값: 3.58
최소값: 0.41


color_intensity
평균: 5.1
중간값: 4.7
표준편차: 2.3
최대값: 13.0
최소값: 1.28


hue
평균: 1.0
중간값: 1.0
표준편차: 0.2
최대값: 1.71
최소값: 0.48


od280/od315_of_diluted_wines
평균: 2.6
중간값: 2.8
표준편차: 0.7
최대값: 4.0
최소값: 1.27


proline
평균: 746.9
중간값: 673.5
표준편차: 314.0
최대값: 1680.0
최소값: 278.0




평균과 중간값의 차이가 크지 않고 

중간값과 평균의 차가 표준편차를 넘지 않기 때문에 대표값을 평균으로 정했습니다.

In [16]:
for i in range(len(wine.feature_names)):  
  print("대표값은:",wine.feature_names[i],"의 평균인",round(np.mean(wine.data[:,i]),1),"입니다.")

대표값은: alcohol 의 평균인 13.0 입니다.
대표값은: malic_acid 의 평균인 2.3 입니다.
대표값은: ash 의 평균인 2.4 입니다.
대표값은: alcalinity_of_ash 의 평균인 19.5 입니다.
대표값은: magnesium 의 평균인 99.7 입니다.
대표값은: total_phenols 의 평균인 2.3 입니다.
대표값은: flavanoids 의 평균인 2.0 입니다.
대표값은: nonflavanoid_phenols 의 평균인 0.4 입니다.
대표값은: proanthocyanins 의 평균인 1.6 입니다.
대표값은: color_intensity 의 평균인 5.1 입니다.
대표값은: hue 의 평균인 1.0 입니다.
대표값은: od280/od315_of_diluted_wines 의 평균인 2.6 입니다.
대표값은: proline 의 평균인 746.9 입니다.
